
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 28 21:08:59 EST 2014
//----------------------------------------------------

package common.exec.z3;

/** CUP generated class containing symbol constants. */
public class Syms {
  /* terminals */
  public static final int NUM = 15;
  public static final int UNSAT = 3;
  public static final int INT = 7;
  public static final int DEFINE = 10;
  public static final int BOOL = 8;
  public static final int MODEL = 2;
  public static final int TRUE = 5;
  public static final int ERROR = 9;
  public static final int STRING = 13;
  public static final int EOF = 0;
  public static final int RB = 12;
  public static final int FALSE = 6;
  public static final int ID = 14;
  public static final int LB = 11;
  public static final int error = 1;
  public static final int SAT = 4;
}

